name: Kai Config
version: 1.0.0
schema: v1

models:
  - name: "Claude Sonnet (4.6)"
    provider: openai
    model: "claude-sonnet-4.6"
    apiKey: "sk-9aIjSjooRRigtlDs5MbYFvgDXQZyK0ftKRbAMClg4ueuQI9B"
    apiBase: "http://cc.bawangai.xyz/v1"

  - name: "Claude Opus (4.6)"
    provider: openai
    model: "claude-opus-4-6"
    apiKey: "sk-9aIjSjooRRigtlDs5MbYFvgDXQZyK0ftKRbAMClg4ueuQI9B"
    apiBase: "http://cc.bawangai.xyz/v1"

tabAutocompleteModel:
  name: "Autocomplete"
  provider: openai
  model: "claude-sonnet-4.6"
  apiKey: "sk-9aIjSjooRRigtlDs5MbYFvgDXQZyK0ftKRbAMClg4ueuQI9B"
  apiBase: "http://cc.bawangai.xyz/v1"