name: Continue
version: 2.0.0
models:
  - title: "Claude 3.5 Sonnet (4.6)"
    provider: "openai"
    model: "claude-sonnet-4.6"
    apiKey: "sk-rLpaZXs3l4Ki2eqp1LW9kFRNt1bPob9jSGXoLnayqjqGtAt7"
    apiBase: "https://leexx.site/v1"

  - title: "Claude 3 Opus (4.6)"
    provider: "openai"
    model: "claude-opus-4-6"
    apiKey: "sk-rLpaZXs3l4Ki2eqp1LW9kFRNt1bPob9jSGXoLnayqjqGtAt7"
    apiBase: "https://leexx.site/v1"

tabAutocompleteModel:
  title: "Autocomplete"
  provider: "openai"
  model: "claude-sonnet-4.6"
  apiKey: "sk-rLpaZXs3l4Ki2eqp1LW9kFRNt1bPob9jSGXoLnayqjqGtAt7"
  apiBase: "https://leexx.site/v1"

contextProviders:
  - name: code
  - name: docs
  - name: diff
  - name: terminal

slashCommands:
  - name: edit
    description: Edit selected code
  - name: comment
    description: Write comments for selected code
